# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grafica.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Grafica(object):
    def setupUi(self, Grafica):
        Grafica.setObjectName("Grafica")
        Grafica.resize(800, 600)
        Grafica.setAcceptDrops(True)
        Grafica.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"border-color: rgb(255, 255, 255);\n"
"selection-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Grafica)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 50, 368, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(56, 56, 56);")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        Grafica.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Grafica)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        Grafica.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Grafica)
        self.statusbar.setObjectName("statusbar")
        Grafica.setStatusBar(self.statusbar)

        self.retranslateUi(Grafica)
        QtCore.QMetaObject.connectSlotsByName(Grafica)

    def retranslateUi(self, Grafica):
        _translate = QtCore.QCoreApplication.translate
        Grafica.setWindowTitle(_translate("Grafica", "Gráfica"))
        self.label.setText(_translate("Grafica", "Gráfica"))
        
    def closeEvent(self, event):
          close = QMessageBox()
          close.setWindowTitle("Salir...")
          close.setText("¿Deseas salir?")
          close.setIcon(QMessageBox.Question)
          close.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
          close.setStyleSheet("color: rgb(255, 255, 255); background-color: rgb(64, 64, 64);")
          close = close.exec()

          if close == QMessageBox.Yes:
             event.accept()
          else:
             event.ignore()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Grafica = QtWidgets.QMainWindow()
    ui = Ui_Grafica()
    ui.setupUi(Grafica)
    Grafica.show()
    sys.exit(app.exec_())
