# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'presionactual.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewWindoe(object):
    def setupUi(self, NewWindoe):
        NewWindoe.setObjectName("NewWindoe")
        NewWindoe.resize(410, 230)
        NewWindoe.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"border-color: rgb(255, 255, 255);\n"
"selection-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(NewWindoe)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 368, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(56, 56, 56);")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(70, 70, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label2.setFont(font)
        self.label2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("Aaaaaa")
        NewWindoe.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(NewWindoe)
        self.statusbar.setObjectName("statusbar")
        NewWindoe.setStatusBar(self.statusbar)

        self.retranslateUi(NewWindoe)
        QtCore.QMetaObject.connectSlotsByName(NewWindoe)

    def retranslateUi(self, NewWindoe):
        _translate = QtCore.QCoreApplication.translate
        NewWindoe.setWindowTitle(_translate("NewWindoe", "Presión Actual"))
        self.label.setText(_translate("NewWindoe", "Presión Actual"))
        self.label2.setText(_translate("NewWindoe", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewWindoe = QtWidgets.QMainWindow()
    ui = Ui_NewWindoe()
    ui.setupUi(NewWindoe)
    NewWindoe.show()
    sys.exit(app.exec_())
